# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{59826a4f-abcf-4d1f-b049-c236572bc823}',
        'contract_ids': ['@mozilla.org/aswebauthsession-content-policy;1'],
        'esModule': 'moz-src:///browser/modules/ASWebAuthSessionService.sys.mjs',
        'constructor': 'ASWebAuthSessionCallbackContentPolicy',
        'categories': {
            'content-policy': '@mozilla.org/aswebauthsession-content-policy;1',
        },
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
