[telemetry.sub.https.window.html]
  [Closing notification without clicking]
    expected:
      # Bug 2067862
      if os == "android": [PASS, FAIL]
  [Closing notification]
    expected:
      # Bug 2067862
      if os == "android": [PASS, FAIL]

